In [1]:
import pandas as pd
from sklearn.datasets import load_breast_cancer


In [2]:
data = load_breast_cancer()
dataset = pd.DataFrame(data=data['data'], columns=data['feature_names'])
dataset.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

#### Split the dataset

In [3]:
from sklearn.model_selection import train_test_split

X = dataset.copy()
y = data['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33)

In [10]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(max_depth=4)
clf = clf.fit(X_train, y_train)

In [11]:
clf.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 4,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [12]:
X_test.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
402        12.96         18.29           84.18      525.2          0.07351   
2          19.69         21.25          130.00     1203.0          0.10960   
414        15.13         29.81           96.71      719.5          0.08320   
132        16.16         21.54          106.20      809.8          0.10080   
300        19.53         18.90          129.50     1217.0          0.11500   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
402           0.07899         0.04057              0.01883         0.1874   
2             0.15990         0.19740              0.12790         0.2069   
414           0.04605         0.04686              0.02739         0.1852   
132           0.12840         0.10430              0.05613         0.2160   
300           0.16420         0.21970              0.10620         0.1792   

     mean fractal dimension  ...  worst radius  worst texture  \
402                 0.05899  ...         14.13          24.61   
2                   0.05999  ...         23.57          25.53   
414                 0.05294  ...         17.26          36.91   
132                 0.05891  ...         19.47          31.68   
300                 0.06552  ...         25.93          26.24   

     worst perimeter  worst area  worst smoothness  worst compactness  \
402            96.31       621.9           0.09329            0.23180   
2             152.50      1709.0           0.14440            0.42450   
414           110.10       931.4           0.11480            0.09866   
132           129.70      1175.0           0.13950            0.30550   
300           171.10      2053.0           0.14950            0.41160   

     worst concavity  worst concave points  worst symmetry  \
402           0.1604               0.06608          0.3207   
2             0.4504               0.24300          0.3613   
414           0.1547               0.06575          0.3233   
132           0.2992               0.13120          0.3480   
300           0.6121               0.19800          0.2968   

     worst fractal dimension  
402                  0.07247  
2                    0.08758  
414                  0.06165  
132                  0.07619  
300                  0.09929  

[5 rows x 30 columns]

In [13]:
predictions = clf.predict(X_test)
predictions

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1])

In [15]:
clf.predict_proba(X_test)

# in the above, the predictions will show as 0 or 1 if the classifier does not have the "max_depth" variable set.

array([[0.00900901, 0.99099099],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.19047619, 0.80952381],
       [0.00900901, 0.99099099],
       [0.00900901, 0.99099099],
       [1.        , 0.        ],
       [0.00900901, 0.99099099],
       [0.19047619, 0.80952381],
       [0.00900901, 0.99099099],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.00900901, 0.99099099],
       [0.00900901, 0.99099099],
       [1.        , 0.        ],
       [0.00900901, 0.99099099],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.00900901, 0.99099099],
       [0.00900901, 0.99099099],
       [0.00900901, 0.99099099],
       [0.00900901, 0.99099099],
       [0.00900901, 0.99099099],
       [1.        , 0.        ],
       [0.00900901, 0.99099099],
       [1.        , 0.        ],
       [0.00900901, 0.99099099],
       [1.

In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.9414893617021277

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions, labels=[0,1])

array([[ 68,   6],
       [  5, 109]])

In [20]:
from sklearn.metrics import precision_score
precision_score(y_test, predictions)

np.float64(0.9478260869565217)

In [21]:
from sklearn.metrics import recall_score
recall_score(y_test, predictions)

np.float64(0.956140350877193)